[versions]
agp = "8.2.2"

coreKtx = "1.10.1"
junit = "4.13.2"

lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"

skiko = "0.7.85"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

skiko = { group = "org.jetbrains.skiko", name = "skiko-awt", version.ref = "skiko" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
